WebApp/Controllers/UsuarioController.cs
using Dominio;
using Microsoft.AspNetCore.Mvc;
using WebApp.Filters;

namespace WebApp.Controllers
{
    
    public class UsuarioController : Controller
    {
        private Sistema sistema = Sistema.Instancia;

           // registro controller: 
        [HttpGet]
        public IActionResult Registro()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Registro(Ocasional ocasioanal)
        {
            try
            {
                if (string.IsNullOrEmpty(ocasioanal.Correo) || string.IsNullOrEmpty(ocasioanal.Contrasenia)
                    || string.IsNullOrEmpty(ocasioanal.Nombre)
                    || string.IsNullOrEmpty(ocasioanal.Documento) || string.IsNullOrEmpty(ocasioanal.Nacionalidad))
                {
                    ViewBag.Mensaje = "Debe completar todos los campos";
                    return View();
                }

                if (ocasioanal.Contrasenia.Length < 8 || !EsAlfanumerica(ocasioanal.Contrasenia))
                {
                    ViewBag.Mensaje = "La contraseña debe ser alfanumérica y tener al menos 8 caracteres.";
                    return View();
                }

                bool agregado = sistema.RegistrarCliente(ocasioanal);
                if (!agregado)
                {
                    ViewBag.Mensaje = "El correo ya está registrado.";
                    return View();
                }

                // Login automático
                HttpContext.Session.SetString("correo", ocasioanal.Correo);
                HttpContext.Session.SetString("rol", "Ocasional");

                return RedirectToAction("Index", "Home");
            }
            catch (Exception ex)
            {
                ViewBag.Mensaje = ex.Message;
                return View();
            }
        }

        private bool EsAlfanumerica(string texto)
        {
            for (int i = 0; i < texto.Length; i++)
            {
                if (!char.IsLetterOrDigit(texto[i]))
                {
                    return false;
                }
            }
            return true;
        }
        [HttpGet]
        public IActionResult Login(string mensaje)
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login(string correo, string contrasenia)
        {
            try
            {
                if (string.IsNullOrEmpty(correo) && string.IsNullOrEmpty(contrasenia))
                {
                    ViewBag.Mensaje = "Ingrese datos";
                }
                else
                {
                    Usuario usuario = sistema.BusarUsuario(correo);
                    if (usuario != null)
                    {
                        if (usuario.Contrasenia == contrasenia)
                        {
                            string nombreTipo = usuario.GetType().Name; //name (devuelve como una cadena string:)
                            HttpContext.Session.SetString("correo", usuario.Correo);
                            HttpContext.Session.SetString("rol", usuario.GetType().Name);

                        }
                        return RedirectToAction("Index", "Home");

                    }
                }
            }
            catch (Exception ex)
            {
                ViewBag.Mensaje = ex.Message;
            }
            return View();
        }

        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Login");
        }
        [Authentication]
        // Ver el perfil del cliente: 
        public IActionResult VerPerfil()
        {
            string correo = HttpContext.Session.GetString("correo");

            if (string.IsNullOrEmpty(correo))
            {
                return RedirectToAction("Login", "Acceso");
            }

            Usuario usuario = sistema.BusarUsuario(correo);

            if (usuario == null || !(usuario is Cliente))
            {
                return RedirectToAction("Login", "Acceso");
            }

            return View(usuario as Cliente);
        }
     
    }
}

WebApp/Controllers/VueloController.cs
using Dominio;
using Microsoft.AspNetCore.Mvc;
using WebApp.Filters;

namespace WebApp.Controllers
{
    [Authentication]
    public class VueloController : Controller
    {
        Sistema sistema = Sistema.Instancia;
        public IActionResult Index()
        {
            return View();
        }
        [ClienteFilter]
        public IActionResult VerVuelos()
        {
            List<Vuelo> vuelos = sistema.ObtenerVuelos();
            ViewBag.Vuelos = vuelos;
            return View();
        }

        [HttpPost]
        public IActionResult BuscarVueloPorRuta(string iataSalida, string iataLlegada)
        {
            List<Vuelo> vuelos = sistema.ObtenerVuelosPorRuta(iataSalida, iataLlegada);
            ViewBag.Vuelos = vuelos;
            return View("VerVuelos");
        }

        // ver detalle de los Vuelos
        public IActionResult Detalle(string id)
        {
            try
            {
                Vuelo vuelo = sistema.ObtenerVueloPorId(id);
                return View(vuelo);
            }
            catch (Exception ex)
            {
                return RedirectToAction("Detalle", new { mensaje = ex.Message }); 
            }

        }
        // tipo de equipaje: 
        public IActionResult Add()
        {
            return View(sistema.Pasajes);
        }
    }
}

WebApp/Views/shared/layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (Context.Session.GetString("correo") != null)
                        {
                            if (Context.Session.GetString("rol") == "Administrador")
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-danger fw-semibold" asp-controller="Usuario" asp-action="Logout">Cerrar Sesión</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-primary fw-semibold" asp-controller="Administrador" asp-action="VerClientes">Ver Clientes</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-success fw-semibold" asp-controller="Pasaje" asp-action="VerPasajes">Ver Pasajes</a>
                                </li>

                            }

                            else
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-primary fw-semibold" asp-controller="Usuario" asp-action="VerPerfil">Ver perfil</a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link text-success fw-semibold" asp-controller="Vuelo" asp-action="VerVuelos">Ver Vuelos</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-danger fw-semibold" asp-controller="Usuario" asp-action="Logout">Cerrar Sesión</a>
                                </li>
                                
                                <li class="nav-item">
                                    <a class="nav-link text-primary fw-semibold" asp-controller="Pasaje" asp-action="MisPasajes">Mis Pasajes</a>
                                </li>
                            }

                          
                           
                           
                            
                       
                            
                        }
                    </ul>
                </div>

            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>